from pathlib import Path
import json,re,copy,hashlib,sys
from html import escape
from lxml import html
W=Path(__file__).resolve().parent; R=W.parent.parent
sys.path.insert(0,str(R/'codex_tools'))
from freshness_guard import validate
validate(W)
db=R/'data/posts_db.json'; before=W/'posts_db.before.json'
if not before.exists(): before.write_bytes(db.read_bytes())
posts=json.loads(db.read_text(encoding='utf-8-sig'))
original={p['slug']:p for p in json.loads(before.read_text(encoding='utf-8-sig'))}
S='sleep-lying-down-eyes-closed-20min-rule.html'; H='sleep-hygiene-guide.html'
def p(t):return '<p style="font-size:1.02rem;line-height:1.9;color:#334155;margin-bottom:22px;">'+t+'</p>'
def ps(*ts):return '\n'.join(p(t) for t in ts)
def h(i,t):return f'<h2 id="section{i}">{t}</h2>'
def toc(heads):return '<div class="toc-box"><div class="toc-title">목차</div><ul class="toc-list">'+''.join(f'<li><a href="#section{i}">{t}</a></li>' for i,t in enumerate(heads,1))+'</ul></div>'
def photo(slug,n,cap):
 imgs=html.fromstring(original[slug]['bodyHtml']).xpath('//img')
 src=imgs[n-1].get('src')
 return f'<figure class="post-photo-figure"><img src="{src}" alt="{cap}" loading="lazy" decoding="async"><figcaption>{cap}</figcaption></figure>'
def table(headers,rows):return '<div class="custom-data-table-wrap" style="overflow-x:auto;margin:28px 0;border:1px solid #e2e8f0;border-radius:10px;"><table class="custom-data-table" style="width:100%;min-width:560px;border-collapse:collapse;"><thead><tr>'+''.join('<th>'+x+'</th>' for x in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+x+'</td>' for x in row)+'</tr>' for row in rows)+'</tbody></table></div>'
def card(title,rows):return '<div class="info-section-card"><div class="info-card-title">'+title+'</div><div class="info-step-list">'+''.join('<div class="info-step-item"><span class="info-badge blue">'+a+'</span><div class="info-step-desc">'+b+'</div></div>' for a,b in rows)+'</div></div>'
def ref(url,title,note):return f'<a href="{url}" target="_blank" rel="noopener noreferrer">{title}</a> — {note}'
def correction():return p('<small>내용 확인·수정: 2026년 9월 14일. 연구의 발표 연도와 아래 원문을 대조해 효과를 단정한 표현과 생활 안내를 정리했습니다.</small>')
A='https://pmc.ncbi.nlm.nih.gov/articles/PMC7853203/'
B='https://pubmed.ncbi.nlm.nih.gov/31102877/'
N='https://www.nhs.uk/every-mind-matters/mental-wellbeing-tips/how-to-fall-asleep-faster-and-sleep-better/'
L='https://pubmed.ncbi.nlm.nih.gov/31138694/'
M='https://www.nccih.nih.gov/health/sleep-disorders-and-complementary-health-approaches'
T='https://www.nhlbi.nih.gov/health/insomnia/treatment'
V='https://healthquality.va.gov/HEALTHQUALITY/guidelines/CD/insomnia/I-OSA-CPG_2025-Guideline_final_20250915.pdf'
heads=['눈을 감는 휴식과 잠은 다릅니다','침대에서 조급해지는 이유를 살펴요','20분보다 중요한 것은 졸림입니다','샤워 시간을 공식처럼 맞추지 마세요','보조제보다 먼저 살필 저녁 습관']
body=ps('잠 안 올 때 눈만 감고 누워 있어도 도움이 될까요?','불을 끄고 휴대전화까지 내려놓았는데 잠이 오지 않으면, 이 시간이라도 피로가 풀리고 있는지 궁금해집니다.','<strong>편안히 쉬는 것이 헛수고는 아니지만, 눈을 감은 휴식이 잠을 대신하지는 않습니다.</strong>','그렇다고 잠깐 깨어 있었다는 이유로 뇌가 망가지거나 불면증이 생긴다고 걱정할 필요도 없습니다.')+toc(heads)
body+=h(1,heads[0])+ps('영국 NHS는 편안하게 누워 쉬는 동안 자연스럽게 잠들 수도 있으니 억지로 잠을 청하지 말라고 안내합니다.','눈을 감았다는 사실만으로 뇌가 전혀 쉬지 못한다거나 피로가 절반 회복된다고 계산할 수는 없습니다.','미국 국립심장폐혈액연구소(NHLBI)는 잠을 비렘 수면과 렘 수면으로 나누며, 비렘 수면 안에도 여러 단계가 있다고 설명합니다.','휴식과 수면의 차이를 알려면 뇌파 등 여러 신호가 필요하므로, 누워 있는 자세나 눈을 감은 시간만으로 깊은 잠에 들었는지 판단하기 어렵습니다.','<strong>깊은 잠의 역할을 강조하려고 깨어 있는 휴식을 쓸모없다고 설명하면 오히려 잠에 대한 부담만 커질 수 있습니다.</strong>')+photo(S,1,'잠이 오지 않아 침대에서 쉬는 모습')
body+=h(2,heads[1])+ps('문제는 눈을 감는 행동 자체보다 침대에서 오래 초조해지는 일이 반복되는 경우입니다.','NHLBI가 설명하는 자극조절은 침대와 잠의 연결을 되찾도록 돕는 방법으로, 졸릴 때 눕고 잠이 안 오면 잠시 침대에서 나오는 행동을 포함합니다.','이를 "20분을 넘기면 불면증이 시작된다"는 경계선으로 받아들일 필요는 없습니다.','잠이 안 온다고 자꾸 시계를 보거나 내일의 피로를 계산하면 걱정이 커질 수 있으니, 시간을 확인하기 쉬운 화면부터 치워보세요.')+table(['지금 상태','어떻게 이해할까요','다음 행동'],[['편안하게 쉬며 졸리는 중','잠들기 전의 휴식일 수 있음','억지로 잠을 재촉하지 않기'],['깨어 있는 느낌이 길고 답답함','침대에서 초조해지는 패턴 살피기','잠시 자리를 옮겨 조용히 쉬기'],['여러 날 반복되고 낮에도 힘듦','수면 환경 외의 원인도 확인 필요','생활 기록을 가지고 진료받기']])
body+=h(3,heads[2])+ps('NHS가 제시하는 방법은 약 20분 뒤에도 깨어 있다면 편안한 곳으로 옮겨 책을 읽거나 조용한 음악을 듣는 것입니다.','다시 침대로 돌아갈 때의 기준은 시간이 얼마나 지났는지가 아니라 졸음이 오는지입니다.','<strong>알람을 맞추거나 마음속으로 분을 세기보다, 잠이 오지 않아 답답해졌다는 느낌을 기준으로 삼아보세요.</strong>','일어날 때는 천천히 움직이고, 발밑이 보일 만큼의 빛은 남겨 두는 편이 좋습니다.','거실에서 밀린 업무나 집안일을 시작하면 쉬는 시간이 다시 활동 시간이 되기 쉬우니, 조용히 머물 수 있는 일을 골라보세요.')+photo(S,3,'잠시 쉬기 위해 마련한 거실 의자')+ps('한 번 자리를 옮겼다고 바로 잠들어야 하는 것은 아닙니다.','미국수면의학회(AASM)의 2021년 지침도 행동·심리적 접근의 효과는 점진적으로 나타날 수 있다고 설명합니다.')+photo(S,4,'졸음이 올 때까지 조용히 책을 읽는 모습')
body+=h(4,heads[3])+ps('따뜻한 샤워나 목욕은 잠들기 전 긴장을 풀 때 활용할 수 있지만, 시간을 맞추면 누구나 곧바로 잠드는 공식은 아닙니다.','2019년 《Sleep Medicine Reviews》에 실린 문헌고찰에서는 <strong>취침 1~2시간 전 따뜻한 물에 약 10분 이상 몸을 데우는 방식</strong>과 입면 시간 단축의 연관이 보고됐습니다.','다만 포함된 연구가 제한적이어서 효과적인 시간과 지속 시간에는 추가 연구가 필요하다는 한계도 함께 제시됐습니다.','따라서 "정확히 90분 전", "입면 속도 2배", "10분 만에 깊은 잠"으로 단정할 근거가 되지는 않습니다.','연구에서 사용한 물 온도를 억지로 따라 하기보다 뜨겁거나 어지러울 정도의 목욕은 피하고, 샤워 뒤 편안하게 쉴 여유를 두세요.')
body+=h(5,heads[4])+ps('저녁 빛은 멜라토닌 분비에 영향을 주지만, 휴대전화를 보면 누구나 같은 비율로 줄어드는 것은 아닙니다.','2019년 《PNAS》의 저녁 빛 노출 연구에서도 개인마다 반응의 차이가 크게 나타났습니다.','화면의 색만 바꾸는 데 집중하기보다 밝기를 낮추고 사용 시간을 줄여, 잠자리에서 계속 영상을 넘겨보는 흐름을 끊어보세요.','마그네슘 역시 "잠들기 한 시간 전에 먹으면 숙면에 좋다"는 공통 복용법으로 소개하기 어렵습니다.','미국 NCCIH 안내와 2025년 VA/DoD 지침은 불면증에 대한 마그네슘 근거가 충분하지 않다는 점을 짚습니다.','이미 복용하는 약이나 보충제가 있다면 임의로 시간·양을 바꾸지 말고 의사나 약사에게 확인하세요.')+card('오늘 밤 부담 없이 확인할 것',[('잠자리','시간을 계산하며 버티기보다 졸림과 편안함을 살펴보세요.'),('저녁','밝은 화면과 늦은 카페인, 잠들기 위한 음주를 돌아보세요.'),('반복될 때','생활수칙만으로 해결하려 애쓰지 말고 원인 확인과 도움을 받으세요.')])+ps('NHLBI는 카페인과 취침 전 음주를 피하고 일정한 수면 일정을 유지하는 습관을 안내합니다.','식후 커피가 궁금하다면 <a href="coffee-after-meal-golden-time.html">커피와 철분 흡수, 복용 간격</a>을, 침실을 점검하려면 <a href="sleep-hygiene-guide.html">수면 위생과 침실 환경 안내</a>를 함께 살펴보세요.','생활습관을 바꿔도 낮의 집중력이나 일상생활에 영향을 줄 만큼 문제가 이어진다면 진료를 받는 것이 좋습니다.','만성 불면증에는 불면증 인지행동치료(CBT-I)가 권고되며, 수면 위생만으로 모든 문제가 해결되는 것은 아닙니다.')+photo(S,5,'침실로 돌아와 편안하게 누운 모습')+ps('오늘 밤의 목표를 "반드시 빨리 잠들기"에서 "잠을 재촉하는 부담 줄이기"로 바꿔보세요.','잘 자야 한다는 숙제에 작은 여유를 더하는 것부터 시작해도 괜찮습니다.')+correction()
s=next(x for x in posts if x['slug']==S)
s.update(title='잠 안 올 때 눈만 감고 누워 있어도 될까? 휴식과 수면의 차이·침대 20분 수칙',shortTitle='잠 안 올 때 눈만 감고 누워 있어도 될까?',desc='눈을 감은 휴식과 수면의 차이, 잠이 오지 않을 때 자리를 옮기는 요령과 샤워·조명·보조제 근거를 확인합니다.',bodyHtml=body,academicSource='AASM·NHLBI 수면 지침과 관련 연구 원문 대조')
s['faqs']=[{'q':'침대에서 나왔을 때 휴대전화로 조용한 영상을 봐도 될까요?','a':'NHS는 독서나 조용한 음악 등 편안한 활동을 제안합니다. 화면의 빛과 계속 바뀌는 내용이 신경 쓰인다면 화면을 보지 않는 활동을 골라보세요. 멜라토닌 감소율을 일률적으로 계산할 수는 없습니다.'},{'q':'마그네슘을 먹는 시간을 바꾸면 잠이 나아질까요?','a':'NCCIH와 2025년 VA/DoD 지침에서는 마그네슘의 불면증 효과를 확정할 근거가 부족하다고 설명합니다. 모든 사람에게 취침 1시간 전 복용을 권할 수 없으며, 복용 여부와 시간은 제품 지침 및 의사·약사의 안내를 따르세요.'},{'q':'잠이 안 오는 일이 반복되면 무엇을 기록하면 좋을까요?','a':'NHLBI는 진료 전 1~2주 동안 수면일지를 적는 방법을 안내합니다. 잠자리에 든 시각과 기상, 낮잠, 낮의 졸림, 카페인·음주 등을 기록하면 생활 패턴을 설명하는 데 도움이 됩니다. 일상에 지장이 있다면 기간을 채우려고 진료를 미루지 마세요.'}]
s['academicRefs']=[ref(A,'AASM (2021) 《Behavioral and psychological treatments for chronic insomnia disorder in adults》','CBT-I와 자극조절의 권고 및 수면위생 단독 접근의 한계.'),ref(N,'NHS 《Fall asleep faster and sleep better》','휴식과 약 20분 후 행동 안내; 페이지 발행일 미확인, 2026-09-14 조회.'),ref(B,'Sleep Medicine Reviews (2019) 《Before-bedtime passive body heating by warm shower or bath to improve sleep》','따뜻한 물 목욕의 시점과 연구 한계.'),ref(L,'PNAS (2019) 《High sensitivity and interindividual variability in the response of the human circadian system to evening light》','저녁 빛에 대한 개인별 반응 차이.'),ref(M,'NCCIH (2024년 5월 개정) 《Sleep Disorders and Complementary Health Approaches》','마그네슘 등 수면 보조 접근의 근거 한계.'),ref(V,'VA/DoD (2025) 《Management of Chronic Insomnia Disorder and Obstructive Sleep Apnea》','마그네슘 권고에 필요한 근거 부족.'),ref(T,'NHLBI (2022) 《Insomnia Treatment》','생활습관과 자극조절·CBT-I 안내.'),ref('https://www.nhlbi.nih.gov/health/insomnia/diagnosis','NHLBI (2022) 《Insomnia Diagnosis》','수면일지와 일상생활 지장 시 진료 안내.'),ref('https://www.nhlbi.nih.gov/health/sleep/stages-of-sleep','NHLBI (2022) 《Sleep Phases and Stages》','비렘·렘 수면의 구분.')]

heads=['멜라토닌은 수면 리듬을 돕습니다','침실은 숫자보다 편안함을 살펴요','늦은 커피와 식사 시간을 돌아봐요','샤워와 취침 시간을 여유 있게 잡아요','기록을 보며 작은 습관부터 바꿔요']
body=ps('수면 위생을 챙기려고 조명을 바꾸고 침실 온도까지 맞췄는데도 아침이 개운하지 않을 때가 있습니다.','그럴 때 "내가 멜라토닌을 충분히 못 만들고 있나?"부터 걱정하기보다 잠드는 과정과 밤중에 깨는 이유를 함께 살펴보세요.','<strong>수면 위생은 잠들기 좋은 생활·환경을 만드는 습관이며, 정해진 설정만으로 수면의 질이 두 배 좋아지는 방법은 아닙니다.</strong>')+toc(heads)
body+=h(1,heads[0])+ps('미국 NCCIH는 멜라토닌을 어둠에 반응해 만들어지며 생체리듬과 수면에 관여하는 호르몬으로 설명합니다.','이를 뇌 노폐물을 직접 씻어내는 세정제처럼 이해하거나, 많이 분비될수록 무조건 더 잘 잔다고 생각할 필요는 없습니다.','저녁 빛의 영향도 사람마다 다릅니다.','2019년 《PNAS》 연구는 젊은 성인에게 저녁 빛을 일정 시간 노출했을 때 멜라토닌 억제 반응에 큰 개인차가 있음을 보여줬습니다.','따라서 "작은 LED나 5 lux 빛만으로 누구나 분비량이 절반 줄어든다"는 식의 설명은 연구 조건을 지나치게 넓힌 것입니다.')+photo(H,1,'커튼과 침구를 정돈한 침실')
body+=h(2,heads[1])+ps('미국 국립심장폐혈액연구소(NHLBI)가 안내하는 기본 방향은 <strong>조용하고 서늘하며 어두운 침실</strong>입니다.','모든 사람에게 같은 온도·습도와 완전한 암막을 요구하는 지침은 아니며, 필요하다면 약한 야간등을 두어도 된다고 설명합니다.','이불을 덮었을 때 땀이 나는지, 창가 소음이나 기기의 불빛 때문에 깨는지부터 살펴보세요.','조절 가능한 항목을 하나씩 바꾸면 나에게 불편한 조건을 찾기 쉽습니다.','암막을 하더라도 밤에 이동하는 통로가 위험하게 어두워지지 않도록 살피고, 불빛은 얼굴로 직접 향하지 않게 두세요.')+card('침실에서 먼저 살펴볼 세 가지',[('빛','커튼 사이 빛과 화면 밝기가 눈에 거슬리는지 확인하세요.'),('온도','추위나 더위로 깨지 않도록 침구와 실내 환경을 조절하세요.'),('소리','반복되는 알림이나 생활 소음을 줄여보세요.')])+ps('수면 단계별로 별도의 온도나 조도를 맞추려 애쓸 필요도 없습니다.','NHLBI에 따르면 밤에는 비렘 수면과 렘 수면이 반복되므로, 특정 단계만 오래 만들겠다는 목표보다 충분한 수면 기회와 편안한 환경을 우선하세요.')
body+=h(3,heads[2])+ps('오후 커피 한 잔이 늘 괜찮았다고 해서 늦은 시간에도 똑같이 괜찮은 것은 아닙니다.','NHLBI는 카페인의 영향이 최대 8시간 이어질 수 있다고 안내하므로, 정해진 오후 시각보다 <strong>내 취침 시각과 카페인에 대한 반응</strong>을 함께 살펴보는 편이 낫습니다.','술은 처음에 졸리게 할 수 있어도 밤중에 깨거나 잠이 얕아지는 원인이 될 수 있어 잠을 부르는 용도로 삼지 않는 것이 좋습니다.','잠들기 전 과식은 피하되, "위장에 음식이 있으면 깊은 잠은 불가능하다"고 단정할 수는 없습니다.')+table(['상황','확인할 습관','바꿔볼 방향'],[['늦은 커피 뒤 잠이 늦어짐','마지막 카페인 시각과 섭취량','양과 시간을 조절해 반응 기록'],['누우면 속이 더부룩함','취침 가까운 큰 식사','과식과 늦은 저녁을 줄이기'],['술을 마신 날 자주 깸','잠을 위해 마시는 음주','술에 기대어 잠들지 않기'],['화면을 보다가 취침이 밀림','잠자리의 기기 사용','화면을 내려놓을 시간 마련']])+ps('식후 커피와 철분제 간격은 수면과 별개의 문제이므로 <a href="coffee-after-meal-golden-time.html">식후 커피의 철분 흡수 안내</a>에서 구분해 확인할 수 있습니다.')
body+=h(4,heads[3])+ps('목욕 시간을 분 단위로 맞추느라 오히려 저녁이 바빠진다면 부담부터 줄여보세요.','2019년 따뜻한 물 목욕 관련 문헌고찰에서 취침 1~2시간 전 시행한 방식은 잠드는 시간 단축과 연관됐지만, 최적 시점에는 추가 연구가 필요했습니다.','"90분 뒤 체온이 반드시 1도 내려가 잠든다"는 약속으로 읽을 수는 없습니다.','따뜻하게 씻은 뒤 책을 읽거나 조용한 음악을 듣는 시간을 마련하되, 물이 지나치게 뜨겁거나 몸이 불편해지면 무리하지 마세요.')+photo(H,2,'책과 찻잔을 놓아둔 저녁 휴식 공간')+ps('NHLBI는 평일과 주말의 수면 일정 차이를 약 1시간 이내로 유지하는 방법을 제안합니다.','주말에 더 잤다고 하루가 잘못된 것은 아니지만, 평일에 충분히 잘 시간을 확보할 수 있는지도 함께 돌아보세요.','아침에는 일상 속에서 바깥빛을 접하고 낮에 몸을 움직이는 시간을 마련할 수 있습니다.','다만 햇빛을 특정 분량만 쬐면 몇 시간 뒤 멜라토닌 타이머가 반드시 켜진다는 고정 공식은 두지 마세요.')
body+=h(5,heads[4])+ps('스마트워치에 깊은 잠이 적게 표시되면 수면 점수부터 만회하고 싶어질 수 있습니다.','AASM의 수면 측정 기기 안내는 소비자용 기기의 정확도가 기종과 소프트웨어 등에 따라 달라진다는 한계를 짚습니다.','숫자 하나만으로 수면 상태를 단정하지 말고, 실제로 얼마나 피곤했는지와 밤에 깬 상황을 함께 보세요.')+photo(H,3,'침구와 베개를 편안하게 정돈한 모습')+ps('진료를 준비한다면 NHLBI가 제안하는 것처럼 1~2주 정도 취침·기상 시각, 낮잠과 낮의 졸림을 적어두면 생활 패턴을 설명하는 데 도움이 됩니다.','이 기록은 점수를 매기려는 숙제가 아니라 나를 깨우는 요인을 찾기 위한 메모입니다.','충분히 잘 기회가 있는데도 문제가 이어지거나 낮 생활에 지장이 생기면 환경만 고치며 버티지 말고 진료를 받으세요.','AASM의 2021년 지침은 만성 불면증에 인지행동치료(CBT-I)를 권고하며, 수면 위생만을 단독 방법으로 쓰는 데에는 한계가 있다고 설명합니다.','잠이 안 와 침대에 오래 머무는 상황은 <a href="sleep-lying-down-eyes-closed-20min-rule.html">눈을 감은 휴식과 침대 20분 수칙</a>에서 따로 다뤘습니다.')+photo(H,4,'아침에 커튼을 열고 하루를 준비하는 모습')+ps('오늘은 침실 전체를 바꾸기보다 나를 불편하게 만드는 한 가지부터 손봐도 좋겠습니다.','알림을 줄이거나 마지막 커피 시간을 앞당기는 작은 변화가 내 생활에 맞는지 차분히 확인해 보세요.')+correction()
s=next(x for x in posts if x['slug']==H)
s.update(title='수면 위생, 멜라토닌만 챙기면 될까? 침실 조명·온도와 카페인·취침 습관 점검',shortTitle='수면 위생과 침실 환경, 무엇부터 바꿀까?',desc='침실 조명과 온도, 늦은 카페인과 목욕 습관을 살펴보고 멜라토닌과 스마트워치 수면 기록의 한계를 구분합니다.',bodyHtml=body,academicSource='공공기관 수면 안내와 AASM 지침 원문 대조',featuredCaption='커튼과 침구를 정돈한 편안한 침실')
s['faqs']=[{'q':'멜라토닌 제품을 오래 먹으면 몸에서 더 이상 만들지 못하나요?','a':'그렇게 단정할 근거로 안내하면 안 됩니다. NCCIH가 강조하는 것은 장기 복용 안전성에 대한 정보가 충분하지 않다는 점입니다. 복용 중인 약과의 관계, 사용 목적과 기간을 의사·약사에게 확인하고 처방받은 제품은 안내에 따라 사용하세요.'},{'q':'깊은 수면 비율이 낮게 찍히면 바로 문제가 있는 건가요?','a':'소비자용 수면 기록은 기기별 추정 방식과 정확도가 다릅니다. 특정 비율만으로 이상을 단정하거나 독소가 남았다고 해석하지 마세요. 반복되는 낮 졸림과 실제 수면 불편을 함께 살펴보고 필요하면 진료 시 기록을 보여주세요.'},{'q':'어두운 방에서 넘어질까 걱정되는데 수면등을 켜도 되나요?','a':'NHLBI는 필요한 경우 약한 야간등을 허용합니다. 눈부시지 않게 밝기와 위치를 조절하고 이동 통로를 안전하게 확보하세요. 모든 사람에게 조도 0의 침실이 필수라는 뜻은 아닙니다.'}]
s['academicRefs']=[ref('https://www.nhlbi.nih.gov/health/sleep-deprivation/healthy-sleep-habits','NHLBI (2022) 《Healthy Sleep Habits》','침실·수면 일정·카페인·저녁 식사와 약한 야간등 안내.'),ref('https://www.nccih.nih.gov/health/melatonin-what-you-need-to-know','NCCIH (2024년 5월 개정) 《Melatonin: What You Need To Know》','멜라토닌의 역할과 장기 복용 안전성의 한계.'),ref(L,'PNAS (2019) 《High sensitivity and interindividual variability in the response of the human circadian system to evening light》','저녁 빛에 대한 개인차.'),ref(B,'Sleep Medicine Reviews (2019) 《Before-bedtime passive body heating by warm shower or bath to improve sleep》','목욕 시점과 입면 연구의 한계.'),ref(A,'AASM (2021) 《Behavioral and psychological treatments for chronic insomnia disorder in adults》','만성 불면증에 대한 행동·심리 접근.'),ref('https://aasm.org/staying-current-with-actigraphy-devices-for-sleep-wake-monitoring/','AASM 《Staying current with actigraphy devices for sleep-wake monitoring》','소비자 수면 측정 기기별 정확도 한계; 2026-09-14 조회.'),ref('https://www.nhlbi.nih.gov/health/insomnia/diagnosis','NHLBI (2022) 《Insomnia Diagnosis》','수면일지와 진료가 필요한 상황.'),ref('https://www.nhlbi.nih.gov/health/sleep/stages-of-sleep','NHLBI (2022) 《Sleep Phases and Stages》','비렘과 렘 수면의 반복.'),ref(T,'NHLBI (2022) 《Insomnia Treatment》','취침 전 음주와 수면 유지의 관계.')]
for s in posts:
 if s['slug'] in (S,H):
  if 'references' in s: s['references']=s['academicRefs']
  assert 40<=len(s['title'])<=60,(s['title'],len(s['title']))
  for k in ['date','slug','slugKey','category','isLatest','isEditorPick','thumb']:
   assert s.get(k)==original[s['slug']].get(k),k
  (W/(s['slug']+'.json')).write_text(json.dumps(s,ensure_ascii=False,indent=2),encoding='utf-8')
db.write_text(json.dumps(posts,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print('Updated two sleep posts; slugs, publication dates, images and picks preserved.')
